language: java

jdk:
  - oraclejdk8

env:
  - SMR_STAGE=DEV AWS_ACCESS_KEY_ID=123 AWS_SECRET_ACCESS_KEY=123 AWS_DEFAULT_REGION=eu-west-1

addons:
  apt:
    packages:
      - ruby
      - python3

install: gem install fakes3

script:
  - fakes3 -r ~/fakes3 -p 4567 > /dev/null 2>&1 &
  - sleep 5
  - cd serverless-mapreduce
  - mvn package
  - cd ../example-project
  - ./package.sh